### PR TITLE
JIRA-22: Use HTTP Basic authentication.

### PR DESCRIPTION
**Pull request by zometer**
I verified the code works against a live hosted Jira instance, and mocked out the connection-specific code in the unit test. However, some of the macro tests are failing, possibly due to the mocking in RenderingTest not playing nicely. If its something relatively straightforward and someone points me in the right direction, I'll see if I can update this PR. 

Thanks.

### CODE REVIEW

**Comment by vmassol** [comment]
I did this:

```
git checkout -b zometer-JIRA-22_basic-auth master
git pull https://github.com/zometer/jira.git JIRA-22_basic-auth
mvn clean install
```

And got:

```
INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ jira-macro-default ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 30 source files to /Users/vmassol/dev/xwiki/jira/jira-macro/jira-macro-default/target/classes
[INFO] Checking validity of components.txt files...
[INFO] Checking content of [file:/Users/vmassol/dev/xwiki/jira/jira-macro/jira-macro-default/src/main/resources/META-INF/components.txt]
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] bootstrap class path not set in conjunction with -source 1.7
[WARNING] No processor claimed any of these annotations: javax.inject.Inject,org.xwiki.component.annotation.Role,javax.inject.Named,javax.inject.Singleton,org.xwiki.properties.annotation.PropertyDescription
[INFO] 2 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/vmassol/dev/xwiki/jira/jira-macro/jira-macro-default/src/main/java/org/xwiki/contrib/jira/macro/internal/source/AbstractJIRADataSource.java:[33,39] package org.apache.commons.codec.binary does not exist
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JIRA - Parent POM .................................. SUCCESS [  3.671 s]
[INFO] JIRA - Config - Parent POM ......................... SUCCESS [  0.628 s]
[INFO] JIRA - Config - Default API ........................ SUCCESS [  6.147 s]
[INFO] JIRA - API ......................................... SUCCESS [  4.206 s]
[INFO] JIRA - Config - Platform API ....................... SUCCESS [ 11.250 s]
[INFO] JIRA - Config - Admin UI ........................... SUCCESS [  5.893 s]
[INFO] JIRA - Macro - Parent POM .......................... SUCCESS [  0.376 s]
[INFO] JIRA - Macro - Default Implementation .............. FAILURE [  0.763 s]
[INFO] JIRA - Macro - Platform-related Implementation ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

Maybe you forgot some dependency update in the pom.xml to add commons codec?

**Comment by zometer** [comment]
Ah, my fault. It seems xwiki-rendering-test included it in the test scope. I code-completed it and assumed it was somewhere in the compile scope.

**Comment by vmassol** [comment]
I'm on it. I'm rewriting it to use HttpClient and WireMock. Hold on.

**Comment by vmassol** [comment]
Ok I have something working but I'm having a hard time using wiremock to validate non-preemptive basic auth... ;)

**Comment by vmassol** [comment]
Indeed, at https://developer.atlassian.com/server/jira/platform/basic-authentication/

I see: 

> Because JIRA permits a default level of access to anonymous users, it does not supply a typical authentication challenge. Some HTTP client software expect to receive an authentication challenge before they will send an authorization header. This means that it may not behave as expected. In this case, you may need to configure it to supply the authorization header, as described above, rather than relying on its default mechanism.

So we do need preemptive basic authentication ;)

**Comment by vmassol** [comment]
Thanks for your PR @zometer 

Honestly I don't know if moving to HttpClient was such a great idea (I thought it would offer more feature, time will tell). OTOH it also brought more complexity.

If you're interested please check my changes and let me know if you agree with them.

Thanks again

**Comment by vmassol** [comment]
@zometer Note that I haven't tested my changes against a real JIRA instance yet. I've just released version 8.5. Would be awesome if you could validate that it works on your jira instance! Thx

**Comment by vmassol** [comment]
Just tested on jira.xwiki.org and it worked for me, cool ;)

**Pull request merged**
